In [87]:
import pandas as pd

df = pd.read_csv("base.csv")
display(df)

,Player Name,Team-name,Age,Position,App,MinP,Goals,Assist,YC,RC,SPG,PS%,AW,MOTM,Rating
0,Robert Lewandowski,Barcelona,34,FW,20(1),1682,15.0,5.0,NaN,1.0,3.8,79,1.6,7.0,7.53
1,Karim Benzema,Real Madrid,35,FW,15,1306,11.0,3.0,1.0,NaN,4.7,87,0.7,4.0,7.45
2,Antoine Griezmann,Atletico,31,AM(CLR) FW,18(7),1693,8.0,8.0,NaN,NaN,2.6,81.5,0.8,5.0,7.45
3,Vinícius Júnior,Real Madrid,22,AM(L) FW,24,2122,8.0,4.0,8.0,NaN,2.5,82.3,NaN,4.0,7.38
4,Pedri,Barcelona,20,AM(CL),18(3),1634,6.0,NaN,2.0,NaN,0.8,88.5,NaN,3.0,7.28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
537,Carlos Álvarez,Sevilla,19,Midfielder,0(1),9,NaN,NaN,1.0,NaN,NaN,100,NaN,NaN,5.89
538,Tomás Alarcón,Cadiz,24,DMC,2(2),222,NaN,NaN,NaN,1.0,0.5,84.3,0.8,NaN,5.82
539,Álvaro Giménez,Cadiz,31,FW,0(1),16,NaN,NaN,NaN,NaN,NaN,100,NaN,NaN,5.82
540,John Donald,Elche,22,D(C),2(1),151,NaN,NaN,NaN,1.0,NaN,87.5,0.7,NaN,5.71
541,Diego López,Rayo Vallecano,41,GK,1,90,NaN,NaN,NaN,NaN,NaN,70.8,NaN,NaN,4.63

In [89]:
df_semgk = df[df["Position"].str.strip() != "GK"].copy()

df_semgk["GP"] = (df_semgk["Goals"] / df_semgk["MinP"]) * 90
df_semgk["AP"] = (df_semgk["Assist"] / df_semgk["MinP"]) * 90

df_900 = df_semgk[df_semgk["MinP"] > 900].copy()

In [90]:
melhores_gols = df_900[["Player Name", "Team-name", "Goals", "MinP", "GP"]].sort_values("GP", ascending=False)
display(melhores_gols.head(10))

            Player Name      Team-name  Goals  MinP        GP
0    Robert Lewandowski      Barcelona   15.0  1682  0.802616
1         Karim Benzema    Real Madrid   11.0  1306  0.758040
51        Álvaro Morata       Atletico   10.0  1326  0.678733
109      Borja Iglesias     Real Betis   11.0  1692  0.585106
7                Joselu       Espanyol   12.0  1909  0.565741
34        Gerard Moreno     Villarreal    6.0  1034  0.522244
52    Alexander Sørloth  Real Sociedad    9.0  1600  0.506250
46          Gabri Veiga     Celta Vigo    8.0  1440  0.500000
17            Enes Ünal         Getafe   12.0  2190  0.493151
292        Ángel Correa       Atletico    5.0   949  0.474183

In [91]:
melhores_assist = df_900[["Player Name", "Team-name", "Assist", "MinP", "AP"]].sort_values("AP", ascending=False)
display(melhores_assist.head(10))

            Player Name        Team-name  Assist  MinP        AP
2     Antoine Griezmann         Atletico     8.0  1693  0.425281
11      Ousmane Dembélé        Barcelona     5.0  1108  0.406137
6          Mikel Merino    Real Sociedad     7.0  1607  0.392035
67     Samuel Chukwueze       Villarreal     5.0  1394  0.322812
244           Ansu Fati        Barcelona     3.0   925  0.291892
8               Rodrygo      Real Madrid     5.0  1546  0.291074
24             Raphinha        Barcelona     4.0  1275  0.282353
120       Gonzalo Plata  Real Valladolid     4.0  1328  0.271084
54           Jordi Alba        Barcelona     3.0  1002  0.269461
0    Robert Lewandowski        Barcelona     5.0  1682  0.267539

In [92]:
piores = df_900[["Player Name", "Team-name", "Goals", "Assist", "MinP", "GP", "AP"]].sort_values(["GP", "AP"], ascending=True)
display(piores.head(10))

          Player Name       Team-name  Goals  Assist  MinP        GP        AP
25      Daniel Parejo      Villarreal    1.0     3.0  2209  0.040742  0.122227
92     Antonio Raíllo        Mallorca    1.0     1.0  2160  0.041667  0.041667
10       Aleix García          Girona    1.0     5.0  2148  0.041899  0.209497
265     Sergio Akieme         Almeria    1.0     NaN  2118  0.042493       NaN
103  Alejandro Catena  Rayo Vallecano    1.0     1.0  2070  0.043478  0.043478
115  Martín Zubimendi   Real Sociedad    1.0     2.0  2051  0.043881  0.087762
88          Moi Gómez         Osasuna    1.0     2.0  2030  0.044335  0.088670
328      Srdjan Babic         Almeria    1.0     NaN  1935  0.046512       NaN
93       Pablo Maffeo        Mallorca    1.0     3.0  1923  0.046802  0.140406
146      Brian Oliván        Espanyol    1.0     5.0  1922  0.046826  0.234131

In [95]:
df_900[["Player Name", "Team-name", "Goals", "Assist", "MinP", "GP", "AP"]].to_excel("eficiencia_jogadores.xlsx", index=False)