In [5]:
import pandas as pd

df = pd.read_csv("base.csv")
display(df)

,Player Name,Team-name,Age,Position,App,MinP,Goals,Assist,YC,RC,SPG,PS%,AW,MOTM,Rating
0,Robert Lewandowski,Barcelona,34,FW,20(1),1682,15.0,5.0,NaN,1.0,3.8,79,1.6,7.0,7.53
1,Karim Benzema,Real Madrid,35,FW,15,1306,11.0,3.0,1.0,NaN,4.7,87,0.7,4.0,7.45
2,Antoine Griezmann,Atletico,31,AM(CLR) FW,18(7),1693,8.0,8.0,NaN,NaN,2.6,81.5,0.8,5.0,7.45
3,Vinícius Júnior,Real Madrid,22,AM(L) FW,24,2122,8.0,4.0,8.0,NaN,2.5,82.3,NaN,4.0,7.38
4,Pedri,Barcelona,20,AM(CL),18(3),1634,6.0,NaN,2.0,NaN,0.8,88.5,NaN,3.0,7.28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
537,Carlos Álvarez,Sevilla,19,Midfielder,0(1),9,NaN,NaN,1.0,NaN,NaN,100,NaN,NaN,5.89
538,Tomás Alarcón,Cadiz,24,DMC,2(2),222,NaN,NaN,NaN,1.0,0.5,84.3,0.8,NaN,5.82
539,Álvaro Giménez,Cadiz,31,FW,0(1),16,NaN,NaN,NaN,NaN,NaN,100,NaN,NaN,5.82
540,John Donald,Elche,22,D(C),2(1),151,NaN,NaN,NaN,1.0,NaN,87.5,0.7,NaN,5.71
541,Diego López,Rayo Vallecano,41,GK,1,90,NaN,NaN,NaN,NaN,NaN,70.8,NaN,NaN,4.63

In [10]:
df900 = df[df['MinP'] > 900]
M = df900[['Player Name','MOTM','Rating']].sort_values("MOTM", ascending=False).dropna(subset=['MOTM'])
display(M)

            Player Name  MOTM  Rating
0    Robert Lewandowski   7.0    7.53
21           Javi Galán   5.0    7.06
2     Antoine Griezmann   5.0    7.45
94          David Soria   5.0    6.74
6          Mikel Merino   5.0    7.23
..                  ...   ...     ...
104        Marcos Acuña   1.0    6.72
99           Unai Núñez   1.0    6.73
98        Omar Alderete   1.0    6.73
97       Iñaki Williams   1.0    6.73
381         Sergio León   1.0    6.30

[117 rows x 3 columns]

In [12]:
M[['Player Name','MOTM','Rating']].to_excel("melhores_da_temp.xlsx", index=False)

In [14]:
M[['Player Name','MOTM','Rating']].sort_values("Rating", ascending=False).head(15)

           Player Name  MOTM  Rating
0   Robert Lewandowski   7.0    7.53
2    Antoine Griezmann   5.0    7.45
1        Karim Benzema   4.0    7.45
3      Vinícius Júnior   4.0    7.38
4                Pedri   3.0    7.28
5    Federico Valverde   4.0    7.26
6         Mikel Merino   5.0    7.23
7               Joselu   4.0    7.22
8              Rodrygo   2.0    7.20
10        Aleix García   2.0    7.19
11     Ousmane Dembélé   2.0    7.18
13    Jeremías Ledesma   4.0    7.11
15        Sergi Darder   4.0    7.10
16     Frenkie de Jong   1.0    7.09
17           Enes Ünal   3.0    7.08